//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleVideoCutter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleVideoCutter.Properties.GlobalStrings", typeof(GlobalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutBox_About {
            get {
                return ResourceManager.GetString("AboutBox_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version is available! Please visit project page..
        /// </summary>
        internal static string AboutBox_NewVersionAvailable {
            get {
                return ResourceManager.GetString("AboutBox_NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string AboutBox_Version {
            get {
                return ResourceManager.GetString("AboutBox_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are running the latest version..
        /// </summary>
        internal static string AboutBox_VersionUpToDate {
            get {
                return ResourceManager.GetString("AboutBox_VersionUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this window you can select from existing FFmpeg profiles (or define a new one) that will be used when converting the video. FFmpeg profile is a set of arguments passed to FFmpeg to cut your video. Don&apos;t worry if you do not know anything about FFmpeg - just press {1} and task will start automatically (using default profile) and this window will not be shown again. But you can always bring it back by holding Shift when clicking on &apos;{0}&apos;.
        ///
        ///TL;DR: just press &apos;{1}&apos;. Window will not be shown again..
        /// </summary>
        internal static string FormAddTask_Explanation {
            get {
                return ResourceManager.GetString("FormAddTask_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to overwrite profile {0}?.
        /// </summary>
        internal static string FormAddTask_OverwwriteProfileQuestion {
            get {
                return ResourceManager.GetString("FormAddTask_OverwwriteProfileQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to same as source.
        /// </summary>
        internal static string FormAddTask_SameAsSource {
            get {
                return ResourceManager.GetString("FormAddTask_SameAsSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default directory when opening video files. 
        ///Can be specified either as absolute path 
        ///or by using one of predefined directories: 
        ///{0}.
        /// </summary>
        internal static string FormSettings_DefaultDirecttoryTooltip {
            get {
                return ResourceManager.GetString("FormSettings_DefaultDirecttoryTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to executable files.
        /// </summary>
        internal static string FormSettings_ExecutableFiles {
            get {
                return ResourceManager.GetString("FormSettings_ExecutableFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output directory where created files are to be saved. 
        ///Can be specified either as absolute path 
        ///or by using one of predefined directories: 
        ///{0}.
        /// </summary>
        internal static string FormSettings_OutputDirectoryTooltip {
            get {
                return ResourceManager.GetString("FormSettings_OutputDirectoryTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern that defines how filenames of created files will be computed. 
        ///Static parts are allowed as well as these pseudo-variable 
        ///  {0} - filename of the original file
        ///  {1} - name of the original file, without extension 
        ///  {2} - extension of the original video file
        ///  {3} - file date of the original video file
        ///  {4} - current timestamp.
        /// </summary>
        internal static string FormSettings_OutputFileNamePatternTooltip {
            get {
                return ResourceManager.GetString("FormSettings_OutputFileNamePatternTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string GlobalCancel {
            get {
                return ResourceManager.GetString("GlobalCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string GlobalClose {
            get {
                return ResourceManager.GetString("GlobalClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string GlobalInformation {
            get {
                return ResourceManager.GetString("GlobalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string GlobalQuestion {
            get {
                return ResourceManager.GetString("GlobalQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All video files.
        /// </summary>
        internal static string MainForm_AllVideoFiles {
            get {
                return ResourceManager.GetString("MainForm_AllVideoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform cut.
        /// </summary>
        internal static string MainForm_ButtonCut {
            get {
                return ResourceManager.GetString("MainForm_ButtonCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default layout will be restored when after application restart..
        /// </summary>
        internal static string MainForm_DeaultLayoutrestoredAfterRestart {
            get {
                return ResourceManager.GetString("MainForm_DeaultLayoutrestoredAfterRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No selection.
        /// </summary>
        internal static string MainForm_NoSelection {
            get {
                return ResourceManager.GetString("MainForm_NoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to use new language settings application needs to be restarted. Do you want to restart now?.
        /// </summary>
        internal static string MainForm_QuestionRestartNewLanguage {
            get {
                return ResourceManager.GetString("MainForm_QuestionRestartNewLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        internal static string MainForm_Selection {
            get {
                return ResourceManager.GetString("MainForm_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string MainForm_Volume {
            get {
                return ResourceManager.GetString("MainForm_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string TaskProcessor_Done {
            get {
                return ResourceManager.GetString("TaskProcessor_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        internal static string TaskProcessor_Failure {
            get {
                return ResourceManager.GetString("TaskProcessor_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed {0} seconds.
        /// </summary>
        internal static string TaskProcessor_Processed {
            get {
                return ResourceManager.GetString("TaskProcessor_Processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string TaskProcessor_State_FinishedError {
            get {
                return ResourceManager.GetString("TaskProcessor_State_FinishedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string TaskProcessor_State_FinishedOK {
            get {
                return ResourceManager.GetString("TaskProcessor_State_FinishedOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress.
        /// </summary>
        internal static string TaskProcessor_State_InProgress {
            get {
                return ResourceManager.GetString("TaskProcessor_State_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled.
        /// </summary>
        internal static string TaskProcessor_State_Scheduled {
            get {
                return ResourceManager.GetString("TaskProcessor_State_Scheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hovered time.
        /// </summary>
        internal static string VideoCutterTimeline_HoveredTime {
            get {
                return ResourceManager.GetString("VideoCutterTimeline_HoveredTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to move clip end.
        /// </summary>
        internal static string VideoCutterTimeline_MoveClipEnd {
            get {
                return ResourceManager.GetString("VideoCutterTimeline_MoveClipEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to move clip start.
        /// </summary>
        internal static string VideoCutterTimeline_MoveClipStart {
            get {
                return ResourceManager.GetString("VideoCutterTimeline_MoveClipStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to middle click to set clip end here
        ///hint: try also with shift/control.
        /// </summary>
        internal static string VideoCutterTimeline_SetClipEndHere {
            get {
                return ResourceManager.GetString("VideoCutterTimeline_SetClipEndHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shift + middle click to set clip from this point till the end.
        /// </summary>
        internal static string VideoCutterTimeline_SetClipFromHereTillEnd {
            get {
                return ResourceManager.GetString("VideoCutterTimeline_SetClipFromHereTillEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shift + middle click to set clip from the beginning till this point.
        /// </summary>
        internal static string VideoCutterTimeline_SetClipFromStartTillHere {
            get {
                return ResourceManager.GetString("VideoCutterTimeline_SetClipFromStartTillHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to middle click to set clip start here
        ///hint: try also with shift/control.
        /// </summary>
        internal static string VideoCutterTimeline_SetClipStartHere {
            get {
                return ResourceManager.GetString("VideoCutterTimeline_SetClipStartHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string VideoCutterTimeline_Time {
            get {
                return ResourceManager.GetString("VideoCutterTimeline_Time", resourceCulture);
            }
        }
    }
}
